### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by pariaspe** [pariaspe/ttb-slam#1]
- [ ] Refactor scan_to_pc: Cleaning and move global vars to attributes

**Comment by RocaPiedra** [comment]
Extras:

- [ ] Voronoi (Topological map)
- [ ] Comparison between exploration algorithms
- [ ] Image recognition of beacons to relocate
